{
  imports = [
    ./hardware-configuration.nix
    ./nixos/kernel/drivers/realtek-88xxau.nix
    ./nixos/nix/auto-upgrade.nix
    ./nixos/services/networking/access-point.nix
    ./nixos/services/networking/wpa-supplicant.nix
    ./nixos/users/accounts.nix
  ];

  disabledModules = [
    ../../modules/nixos/hardware/brillo.nix
    ../../modules/nixos/hardware/intel-hwdec.nix
    ../../modules/nixos/hardware/microcode-updates.nix
    ../../modules/nixos/kernel/drivers/realtek-88xxau.nix
    ../../modules/nixos/kernel/hid/apple-hid.nix
    ../../modules/nixos/kernel/latest.nix
    ../../modules/nixos/programs/browsers.nix
    ../../modules/nixos/programs/browsers.nix
    ../../modules/nixos/programs/emacs.nix
    ../../modules/nixos/programs/gaming.nix
    ../../modules/nixos/programs/hyprland.nix
    ../../modules/nixos/programs/searx.nix
    ../../modules/nixos/programs/theming.nix
    ../../modules/nixos/programs/wireshark.nix
    ../../modules/nixos/services/device/logind.nix
    ../../modules/nixos/services/device/printing.nix
    ../../modules/nixos/services/device/tlp.nix
    ../../modules/nixos/services/device/udev.nix
    ../../modules/nixos/services/filesystem/gvfs.nix
    ../../modules/nixos/services/networking/dnscrypt.nix
    ../../modules/nixos/services/networking/network-manager.nix
    ../../modules/nixos/services/networking/ssh-agent.nix
    ../../modules/nixos/services/security/firejail.nix
    ../../modules/nixos/services/security/gnupg.nix
    ../../modules/nixos/services/security/pam.nix
    ../../modules/nixos/services/sound/pipewire.nix
    ../../modules/nixos/system/bootloader.nix
    ../../modules/nixos/system/virtualisation.nix
  ];
}
